### ISSUE TITLE
backing up database fails due to server version mismatch

### ISSUE THREAD

**Issue by krijnenr** [Expaso/hassos-addon-timescaledb#33]
Backing up a database using pgAdmin4 aborts due to server version mismatch
pg_dump error server version 14.5 pg_dump version 13.8 

Not sure if this is a timescaleDB or pgAdmin4 problem. Is there a way to resolve this?

**Comment by Expaso** [comment]
Hmm.. time to upgrade some stuff.

I will address this issue within pgAdmin. I'm very close to releasing a postgresql 15 version anyway.

**Comment by carhukem** [comment]
After upgrading to the new version 3.0.2 the backup functions are failing because of an older version of pg_dump.

Lof-file of DSMR Reader add-on:
2023-07-22 08:30:41,003 CRITICAL backup on_backup_failed 238 | - Unexpected exit code (1) for backup: b'pg_dump: error: server version: 15.3; pg_dump version: 14.5\npg_dump: error: aborting because of server version mismatch\n'

It seems that PostgreSQL server version is been upgraded to 15.3 but the client portion is not update correctly to same version. Alltough thats my assumption.

Running Home-Assistant on Intel NUC, HA-OS, DSMR-Addon with PostgreSQL - TimeScaleDB Addon enabled.
No specific information on this matter is found on the net, problem just raises a couple a days ago after uprading. So maybe more people are having same issue but aren't aware of that.

**Comment by Klumpke** [comment]
Have the same error after upgrade to version 3.0.2

**Comment by Expaso** [comment]
This issue can be closed because of the new pgAdmin, which gives you a range of postgres tools between postgres 10 and postgres 16
