### ISSUE TITLE
Using the add-on

### ISSUE THREAD

**Issue by Davincible** [Expaso/hassos-addon-timescaledb#9]
First of all, thanks a lot for the work on this extension. Really like the idea of using timescaledb with HA. 

I have some questions about using it. After installing, do I need to do anything extra to make HA use PG as my primary database? I noticed in the closed issues ltss has been discussed, do I need to install that alongside this add-on?

I have looked a bit through the pgAdmin interface, but was unable to locate my data. So how can I view my data/hypertables in the pgAdmin? And how would I query it in e.g. Grafana?

Also, my logs tell my timescaledb is not up to date, as version 2.3.0 is available. And I got the following error, not sure if it has any impact:
```
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: TimescaleDB
 An open-source database built on PostgreSQL for analyzing time-series data with the power and convenience of SQL
-----------------------------------------------------------
 Add-on version: 1.1.6
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[23:21:31] ERROR: Unknown HTTP error occured
 System:   (amd64 / qemux86-64)
 Home Assistant Core: 2021.6.3
 Home Assistant Supervisor: 2021.06.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
```

**Comment by Expaso** [comment]
Hi @Davincible!

Sorry for the late reply. It has been quite busy at my end, so I did not had any time to react sooner.

The error is not critical. It's coming from an automated check between home assistant core and the addon.
If all is well, you'll see the PostgreSQL addon start and simply run. If it stops automatically, there's something wrong.

I am indeed aware of a newer TimescaleDB version.
This new version is also compatible with PostgreSQL 13, so I'm planning on an update of both.

Since upgrading major PostgreSQL version can be quite a pain, it takes a lot of testing. I really hate to break peoples datastores when I make an error, so please be patient.

For replacing the existing datastore in Home Assistant (aka the recorder) , you have to edit your config to point the postgresql datastore.

Please take a look at this link to set it all up:
https://github.com/Expaso/hassos-addons/issues/1

If you have any further questions, please let me know!
